name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # 1) Setup Julia and automatically cache ~/.julia
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'     # or whatever
          cache: true        # <-- turns on caching of your registry/packages/artifacts

      # 2) (If you need Packing3D)
      - name: Pull in Packing3D.jl
        run: julia --project=. -e 'import Pkg; Pkg.develop(url="https://github.com/fjbarter/Packing3D.jl")'

      # 3) Instantiate & test
      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test()'
