name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - name: Install Dependencies and Run Tests
        run: |
          julia --project=. -e 'using Pkg; Pkg.develop(url="https://github.com/fjbarter/Packing3D.jl"); Pkg.instantiate(); import Test; Pkg.add("Test"); Pkg.test("Packing3D")'
